x-net-config:
  &net-config
  network_mode: host
  ipc: host
  env_file: net.env

services:
  rosbot-xl:
    image: husarion/rosbot-xl-manipulation:humble-1.1.0-20230621-stable
    <<: *net-config
    devices:
      - ${MANIPULATOR_SERIAL:?err}:/dev/manipulator
    volumes: 
      - ./config/joy_servo.yaml:/joy_servo.yaml
      - ./config/diff_drive_controller_manipulation.yaml:/ros2_ws/install/rosbot_xl_manipulation_controller/share/rosbot_xl_manipulation_controller/config/diff_drive_controller_manipulation.yaml
    command: >
      ros2 launch rosbot_xl_manipulation_bringup bringup.launch.py
        mecanum:=False
        manipulator_usb_port:=/dev/manipulator
        manipulator_baud_rate:=${MANIPULATOR_BAUDRATE:-115200}
        joy_servo_params_file:=/joy_servo.yaml
        antenna_rotation_angle:=${ANTENNA_ROTATION_ANGLE:- -1.57}

  microros:
    image: husarion/micro-xrce-agent:v2.4.1
    <<: *net-config
    command: MicroXRCEAgent udp4 --port 8888

  rplidar:
    image: husarion/rplidar:humble
    <<: *net-config
    devices:
      - /dev/ttyRPLIDAR:/dev/ttyUSB0
    command: ros2 launch sllidar_ros2 sllidar_launch.py serial_baudrate:=${LIDAR_BAUDRATE:-115200}

  zed:
    image: husarion/zed-desktop-cpu:humble
    <<: *net-config
    volumes:
      - /dev:/dev
    privileged: true
    command: ros2 launch zed_cpu zed.launch

  joy2twist:
    image: husarion/joy2twist:humble-1.0.0-20230204-stable
    <<: *net-config
    devices:
      - /dev/input
    volumes: 
      - ./config/joy2twist.yaml:/joy2twist.yaml
    command: > 
      ros2 launch joy2twist gamepad_controller.launch.py
        joy2twist_params_file:=/joy2twist.yaml