# Usage:
# xhost +local:docker && docker compose -f compose.pc.yaml up

x-net-config:
  &net-config
  network_mode: host
  ipc: host
  env_file: net.env

x-gpu-config:
  &gpu-config
  runtime: nvidia
  environment:
    - DISPLAY=${DISPLAY:?err}
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all

services:
  rviz:
    # Launching rviz with moveit2 requires all the configs, using manipulation simulation image is easiest option
    image: husarion/rosbot-xl-manipulation-gazebo:humble
    <<: [ *net-config, *gpu-config ]
    container_name: rviz
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot_xl.rviz:/ros2_ws/install/rosbot_xl_manipulation_moveit/share/rosbot_xl_manipulation_moveit/config/moveit.rviz
    command: ros2 launch rosbot_xl_manipulation_moveit rviz.launch.py