x-net-config:
  &net-config
  network_mode: host
  ipc: host
  env_file: net.env

x-gpu-config:
  &gpu-config
  runtime: nvidia
  environment:
    - DISPLAY=${DISPLAY:?err}
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all


services:
  rosbot-xl:
    image: husarion/rosbot-xl-manipulation-gazebo:humble
    container_name: rosbot_xl_manipulation_simulation
    <<: [ *net-config, *gpu-config ]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot_xl_manipulation.rviz:/ros2_ws/install/rosbot_xl_manipulation_moveit/share/rosbot_xl_manipulation_moveit/config/moveit.rviz
    command: >
      ros2 launch rosbot_xl_manipulation_gazebo simulation.launch.py
        mecanum:=${MECANUM:-True}
        antenna_rotation_angle:=${ANTENNA_ROTATION_ANGLE:- -1.57}
  
  slam:
    image: husarion/navigation2:humble-1.1.8-20230809
    <<: *net-config
    volumes:
      - ./config/${SLAM_MODE:-slam}_params.yaml:/params.yaml
      - ./maps:/maps
    environment:
      - SLAM_MODE=${SLAM_MODE:-slam}
    command: >
      ros2 launch nav2_bringup ${SLAM_MODE:-slam}_launch.py
        params_file:=/params.yaml
        map:=/maps/map.yaml
        use_sim_time:=False
  
  navigation:
    image: husarion/navigation2:humble-1.1.8-20230809
    <<: *net-config
    depends_on:
      slam: { condition: service_healthy }
    volumes:
      - ./config/nav2_params_mppi.yaml:/nav2_params.yaml
    environment:
      - SLAM_MODE=${SLAM_MODE:-slam}
    command: >
      bash -c "
        if [[ \"\$SLAM_MODE\" == \"localization\" ]]; then 
          ros2 launch nav2_bringup navigation_launch.py 
          params_file:=/nav2_params.yaml 
          use_sim_time:=True; 
        fi
      "

  rosbridge:
    image: husarion/rosbridge-server:humble-1.3.1-20230831
    <<: *net-config
    ports:
      - 9090:9090
    command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml use_compression:=true

  foxglove:
    image: husarion/foxglove:humble-add-panther
    volumes:
      - ./config/foxglove.json:/src/FoxgloveDefaultLayout.json
      - ./config/rosbot_xl_manipulation.urdf:/src/rosbot_xl_manipulation.urdf
    environment:
      - FOXGLOVE_PORT=8080
      - ROSBRIDGE_PORT=9090
    ports:
      - 8080:8080

  joy2twist:
    image: husarion/joy2twist:humble-1.0.0-20230204-stable
    <<: *net-config
    devices:
      - /dev/input
    volumes: 
      - ./config/joy2twist.yaml:/joy2twist.yaml
    command: > 
      ros2 launch joy2twist gamepad_controller.launch.py
        joy2twist_params_file:=/joy2twist.yaml
